--
-- Grants on sys objects 
-- $Id: //Infrastructure/GitHub/Database/asbo/osse/sys_grants.sql#1 $
--
GRANT CONNECT,RESOURCE TO DBAMGR;
ALTER USER DBAMGR QUOTA UNLIMITED ON USERS;
GRANT SELECT ON SYS.V_$LOG to DBAMGR;
GRANT SELECT ON SYS.V_$SESSION to DBAMGR;
GRANT SELECT ON SYS.V_$MYSTAT to DBAMGR;
GRANT SELECT ON SYS.V_$DATABASE to DBAMGR;
GRANT SELECT ON SYS.V_$SQLAREA to DBAMGR;
GRANT SELECT ON SYS.V_$ARCHIVED_LOG to DBAMGR;
GRANT SELECT ON SYS.V_$SESSION_WAIT to DBAMGR;
GRANT SELECT ON SYS.V_$EVENT_NAME to DBAMGR;
GRANT SELECT ON SYS.ACTIVE_SESSION_DETAILS to DBAMGR;
GRANT EXECUTE ON SYS.DBMS_LOCK to DBAMGR;
